[jupiter.server.http]
    port = 6050
[jupiter.server.grpc]
    port = 6055

[jupiter.logger.default]
    debug = false         # 是否在命令行输出
    enableConsole = false # 是否按命令行格式输出
    name = "default.log" # 日志名称
    dir = "."             # 日志路径
    level = "info"       # 调整日志级别，可以动态修改日志

[jupiter.etcdv3.default]
    endpoints=["127.0.0.1:2379"]
    secure = false

[jupiter.registry.bj01]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.registry.bj02]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.cron.demo]
    immediatelyRun = true
    concurrentDelay = 5
[jupiter.mysql.test]
    connMaxLifetime = "300s"
    debug = true
    dsn = "root:123456@tcp(127.0.0.1:3306)/eagle?charset=utf8&parseTime=True&loc=Local"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
    disableTrace = true
    disableMetric = true
[jupiter.trace.jaeger]
    enableRPCMetrics = false
    [jupiter.trace.jaeger.sampler]
        type = "const"
        param = 0.001